### ISSUE TITLE
Mailing list or other opportunity follow data releases

### ISSUE THREAD

**Issue by rexdouglass** [uma-pi1/OPIEC#1]
Congratulations on a fantastic project and result. The project page shows both the full corpus and clean corpus are coming soon. Is there a preferred way to follow updates and data releases, e.g. this github, a twitter account, or a mailing list?

**Comment by gkiril** [comment]
Thank you very much for your kind words! It is always good to see that people find our work relevant. 

I would suggest to follow the README page on https://github.com/gkiril/OPIEC. Whenever there are changes, I will update the README. 

Cheers!
